-- Generated by src.handlers.local_postgres_workbench_deploy
-- Idempotent local PostgreSQL workbench deploy; review before applying.
BEGIN;
CREATE SCHEMA IF NOT EXISTS "staging";
CREATE SCHEMA IF NOT EXISTS "scratch";
CREATE SCHEMA IF NOT EXISTS "review";
CREATE SCHEMA IF NOT EXISTS "evidence";
CREATE TABLE IF NOT EXISTS "staging"."load_manifest" (
  "load_id" text NOT NULL,
  "plan_id" text NOT NULL,
  "provider_slug" text,
  "source_entity" text,
  "source_path" text NOT NULL,
  "source_checksum" text,
  "row_count" bigint,
  "load_status" text NOT NULL,
  "evidence_path" text NOT NULL,
  "loaded_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "pk_staging_load_manifest" PRIMARY KEY ("load_id")
);
ALTER TABLE "staging"."load_manifest" ADD COLUMN IF NOT EXISTS "load_id" text NOT NULL;
ALTER TABLE "staging"."load_manifest" ADD COLUMN IF NOT EXISTS "plan_id" text NOT NULL;
ALTER TABLE "staging"."load_manifest" ADD COLUMN IF NOT EXISTS "provider_slug" text;
ALTER TABLE "staging"."load_manifest" ADD COLUMN IF NOT EXISTS "source_entity" text;
ALTER TABLE "staging"."load_manifest" ADD COLUMN IF NOT EXISTS "source_path" text NOT NULL;
ALTER TABLE "staging"."load_manifest" ADD COLUMN IF NOT EXISTS "source_checksum" text;
ALTER TABLE "staging"."load_manifest" ADD COLUMN IF NOT EXISTS "row_count" bigint;
ALTER TABLE "staging"."load_manifest" ADD COLUMN IF NOT EXISTS "load_status" text NOT NULL;
ALTER TABLE "staging"."load_manifest" ADD COLUMN IF NOT EXISTS "evidence_path" text NOT NULL;
ALTER TABLE "staging"."load_manifest" ADD COLUMN IF NOT EXISTS "loaded_at" timestamptz NOT NULL DEFAULT now();
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pk_staging_load_manifest'
      AND conrelid = 'staging.load_manifest'::regclass
  ) THEN
    ALTER TABLE "staging"."load_manifest" ADD CONSTRAINT "pk_staging_load_manifest" PRIMARY KEY ("load_id");
  END IF;
END $$;
CREATE INDEX IF NOT EXISTS "idx_staging_load_manifest_provider_entity" ON "staging"."load_manifest" ("provider_slug", "source_entity");
CREATE TABLE IF NOT EXISTS "evidence"."local_deploy_runs" (
  "deployment_id" text NOT NULL,
  "plan_id" text NOT NULL,
  "spec_path" text NOT NULL,
  "spec_checksum" text NOT NULL,
  "deploy_status" text NOT NULL,
  "message" text,
  "deployed_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "pk_evidence_local_deploy_runs" PRIMARY KEY ("deployment_id")
);
ALTER TABLE "evidence"."local_deploy_runs" ADD COLUMN IF NOT EXISTS "deployment_id" text NOT NULL;
ALTER TABLE "evidence"."local_deploy_runs" ADD COLUMN IF NOT EXISTS "plan_id" text NOT NULL;
ALTER TABLE "evidence"."local_deploy_runs" ADD COLUMN IF NOT EXISTS "spec_path" text NOT NULL;
ALTER TABLE "evidence"."local_deploy_runs" ADD COLUMN IF NOT EXISTS "spec_checksum" text NOT NULL;
ALTER TABLE "evidence"."local_deploy_runs" ADD COLUMN IF NOT EXISTS "deploy_status" text NOT NULL;
ALTER TABLE "evidence"."local_deploy_runs" ADD COLUMN IF NOT EXISTS "message" text;
ALTER TABLE "evidence"."local_deploy_runs" ADD COLUMN IF NOT EXISTS "deployed_at" timestamptz NOT NULL DEFAULT now();
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pk_evidence_local_deploy_runs'
      AND conrelid = 'evidence.local_deploy_runs'::regclass
  ) THEN
    ALTER TABLE "evidence"."local_deploy_runs" ADD CONSTRAINT "pk_evidence_local_deploy_runs" PRIMARY KEY ("deployment_id");
  END IF;
END $$;
CREATE INDEX IF NOT EXISTS "idx_evidence_local_deploy_runs_plan" ON "evidence"."local_deploy_runs" ("plan_id");
CREATE TABLE IF NOT EXISTS "evidence"."qa_artifact_refs" (
  "artifact_id" text NOT NULL,
  "plan_id" text NOT NULL,
  "artifact_path" text NOT NULL,
  "artifact_kind" text NOT NULL,
  "artifact_checksum" text,
  "record_count" bigint,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "pk_evidence_qa_artifact_refs" PRIMARY KEY ("artifact_id")
);
ALTER TABLE "evidence"."qa_artifact_refs" ADD COLUMN IF NOT EXISTS "artifact_id" text NOT NULL;
ALTER TABLE "evidence"."qa_artifact_refs" ADD COLUMN IF NOT EXISTS "plan_id" text NOT NULL;
ALTER TABLE "evidence"."qa_artifact_refs" ADD COLUMN IF NOT EXISTS "artifact_path" text NOT NULL;
ALTER TABLE "evidence"."qa_artifact_refs" ADD COLUMN IF NOT EXISTS "artifact_kind" text NOT NULL;
ALTER TABLE "evidence"."qa_artifact_refs" ADD COLUMN IF NOT EXISTS "artifact_checksum" text;
ALTER TABLE "evidence"."qa_artifact_refs" ADD COLUMN IF NOT EXISTS "record_count" bigint;
ALTER TABLE "evidence"."qa_artifact_refs" ADD COLUMN IF NOT EXISTS "created_at" timestamptz NOT NULL DEFAULT now();
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pk_evidence_qa_artifact_refs'
      AND conrelid = 'evidence.qa_artifact_refs'::regclass
  ) THEN
    ALTER TABLE "evidence"."qa_artifact_refs" ADD CONSTRAINT "pk_evidence_qa_artifact_refs" PRIMARY KEY ("artifact_id");
  END IF;
END $$;
CREATE INDEX IF NOT EXISTS "idx_evidence_qa_artifact_refs_kind" ON "evidence"."qa_artifact_refs" ("artifact_kind");
CREATE TABLE IF NOT EXISTS "scratch"."normalization_probe_runs" (
  "probe_id" text NOT NULL,
  "iteration_id" text NOT NULL,
  "business_question_id" text,
  "provider_slug" text,
  "source_entity" text,
  "target_entity_candidate" text,
  "scratch_table" text,
  "hypothesis" text NOT NULL,
  "probe_status" text NOT NULL,
  "input_row_count" bigint,
  "output_row_count" bigint,
  "rejected_row_count" bigint,
  "evidence_path" text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "pk_scratch_normalization_probe_runs" PRIMARY KEY ("probe_id")
);
ALTER TABLE "scratch"."normalization_probe_runs" ADD COLUMN IF NOT EXISTS "probe_id" text NOT NULL;
ALTER TABLE "scratch"."normalization_probe_runs" ADD COLUMN IF NOT EXISTS "iteration_id" text NOT NULL;
ALTER TABLE "scratch"."normalization_probe_runs" ADD COLUMN IF NOT EXISTS "business_question_id" text;
ALTER TABLE "scratch"."normalization_probe_runs" ADD COLUMN IF NOT EXISTS "provider_slug" text;
ALTER TABLE "scratch"."normalization_probe_runs" ADD COLUMN IF NOT EXISTS "source_entity" text;
ALTER TABLE "scratch"."normalization_probe_runs" ADD COLUMN IF NOT EXISTS "target_entity_candidate" text;
ALTER TABLE "scratch"."normalization_probe_runs" ADD COLUMN IF NOT EXISTS "scratch_table" text;
ALTER TABLE "scratch"."normalization_probe_runs" ADD COLUMN IF NOT EXISTS "hypothesis" text NOT NULL;
ALTER TABLE "scratch"."normalization_probe_runs" ADD COLUMN IF NOT EXISTS "probe_status" text NOT NULL;
ALTER TABLE "scratch"."normalization_probe_runs" ADD COLUMN IF NOT EXISTS "input_row_count" bigint;
ALTER TABLE "scratch"."normalization_probe_runs" ADD COLUMN IF NOT EXISTS "output_row_count" bigint;
ALTER TABLE "scratch"."normalization_probe_runs" ADD COLUMN IF NOT EXISTS "rejected_row_count" bigint;
ALTER TABLE "scratch"."normalization_probe_runs" ADD COLUMN IF NOT EXISTS "evidence_path" text NOT NULL;
ALTER TABLE "scratch"."normalization_probe_runs" ADD COLUMN IF NOT EXISTS "created_at" timestamptz NOT NULL DEFAULT now();
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pk_scratch_normalization_probe_runs'
      AND conrelid = 'scratch.normalization_probe_runs'::regclass
  ) THEN
    ALTER TABLE "scratch"."normalization_probe_runs" ADD CONSTRAINT "pk_scratch_normalization_probe_runs" PRIMARY KEY ("probe_id");
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'ck_scratch_normalization_probe_runs_status'
      AND conrelid = 'scratch.normalization_probe_runs'::regclass
  ) THEN
    ALTER TABLE "scratch"."normalization_probe_runs" ADD CONSTRAINT "ck_scratch_normalization_probe_runs_status" CHECK (probe_status IN ('planned', 'running', 'passed', 'failed', 'promoted', 'revised', 'needs_hitl', 'rolled_back'));
  END IF;
END $$;
CREATE INDEX IF NOT EXISTS "idx_scratch_normalization_probe_runs_iteration" ON "scratch"."normalization_probe_runs" ("iteration_id", "probe_status");
CREATE TABLE IF NOT EXISTS "review"."hitl_decisions" (
  "decision_id" text NOT NULL,
  "plan_id" text NOT NULL,
  "business_question_id" text,
  "drift_domain" text NOT NULL,
  "source_entity" text,
  "source_field" text,
  "observed_value" text,
  "recommended_option" text,
  "selected_option" text,
  "decision_status" text NOT NULL,
  "reviewer_notes" text,
  "evidence_path" text NOT NULL,
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "pk_review_hitl_decisions" PRIMARY KEY ("decision_id")
);
ALTER TABLE "review"."hitl_decisions" ADD COLUMN IF NOT EXISTS "decision_id" text NOT NULL;
ALTER TABLE "review"."hitl_decisions" ADD COLUMN IF NOT EXISTS "plan_id" text NOT NULL;
ALTER TABLE "review"."hitl_decisions" ADD COLUMN IF NOT EXISTS "business_question_id" text;
ALTER TABLE "review"."hitl_decisions" ADD COLUMN IF NOT EXISTS "drift_domain" text NOT NULL;
ALTER TABLE "review"."hitl_decisions" ADD COLUMN IF NOT EXISTS "source_entity" text;
ALTER TABLE "review"."hitl_decisions" ADD COLUMN IF NOT EXISTS "source_field" text;
ALTER TABLE "review"."hitl_decisions" ADD COLUMN IF NOT EXISTS "observed_value" text;
ALTER TABLE "review"."hitl_decisions" ADD COLUMN IF NOT EXISTS "recommended_option" text;
ALTER TABLE "review"."hitl_decisions" ADD COLUMN IF NOT EXISTS "selected_option" text;
ALTER TABLE "review"."hitl_decisions" ADD COLUMN IF NOT EXISTS "decision_status" text NOT NULL;
ALTER TABLE "review"."hitl_decisions" ADD COLUMN IF NOT EXISTS "reviewer_notes" text;
ALTER TABLE "review"."hitl_decisions" ADD COLUMN IF NOT EXISTS "evidence_path" text NOT NULL;
ALTER TABLE "review"."hitl_decisions" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz NOT NULL DEFAULT now();
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pk_review_hitl_decisions'
      AND conrelid = 'review.hitl_decisions'::regclass
  ) THEN
    ALTER TABLE "review"."hitl_decisions" ADD CONSTRAINT "pk_review_hitl_decisions" PRIMARY KEY ("decision_id");
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'ck_review_hitl_decisions_status'
      AND conrelid = 'review.hitl_decisions'::regclass
  ) THEN
    ALTER TABLE "review"."hitl_decisions" ADD CONSTRAINT "ck_review_hitl_decisions_status" CHECK (decision_status IN ('approved', 'rejected', 'deferred_with_human_approval', 'needs_more_evidence'));
  END IF;
END $$;
CREATE INDEX IF NOT EXISTS "idx_review_hitl_decisions_domain_status" ON "review"."hitl_decisions" ("drift_domain", "decision_status");
CREATE TABLE IF NOT EXISTS "review"."drift_status_values" (
  "drift_id" text NOT NULL,
  "provider_slug" text NOT NULL,
  "source_entity" text NOT NULL,
  "source_field" text NOT NULL,
  "observed_value" text,
  "normalized_candidate" text,
  "observed_count" bigint,
  "review_status" text NOT NULL DEFAULT 'needs_review',
  "decision_id" text,
  "evidence_path" text NOT NULL,
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "pk_review_drift_status_values" PRIMARY KEY ("drift_id")
);
ALTER TABLE "review"."drift_status_values" ADD COLUMN IF NOT EXISTS "drift_id" text NOT NULL;
ALTER TABLE "review"."drift_status_values" ADD COLUMN IF NOT EXISTS "provider_slug" text NOT NULL;
ALTER TABLE "review"."drift_status_values" ADD COLUMN IF NOT EXISTS "source_entity" text NOT NULL;
ALTER TABLE "review"."drift_status_values" ADD COLUMN IF NOT EXISTS "source_field" text NOT NULL;
ALTER TABLE "review"."drift_status_values" ADD COLUMN IF NOT EXISTS "observed_value" text;
ALTER TABLE "review"."drift_status_values" ADD COLUMN IF NOT EXISTS "normalized_candidate" text;
ALTER TABLE "review"."drift_status_values" ADD COLUMN IF NOT EXISTS "observed_count" bigint;
ALTER TABLE "review"."drift_status_values" ADD COLUMN IF NOT EXISTS "review_status" text NOT NULL DEFAULT 'needs_review';
ALTER TABLE "review"."drift_status_values" ADD COLUMN IF NOT EXISTS "decision_id" text;
ALTER TABLE "review"."drift_status_values" ADD COLUMN IF NOT EXISTS "evidence_path" text NOT NULL;
ALTER TABLE "review"."drift_status_values" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz NOT NULL DEFAULT now();
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pk_review_drift_status_values'
      AND conrelid = 'review.drift_status_values'::regclass
  ) THEN
    ALTER TABLE "review"."drift_status_values" ADD CONSTRAINT "pk_review_drift_status_values" PRIMARY KEY ("drift_id");
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'ck_review_drift_status_values_review_status'
      AND conrelid = 'review.drift_status_values'::regclass
  ) THEN
    ALTER TABLE "review"."drift_status_values" ADD CONSTRAINT "ck_review_drift_status_values_review_status" CHECK (review_status IN ('needs_review', 'approved', 'rejected', 'deferred_with_human_approval', 'needs_more_evidence'));
  END IF;
END $$;
CREATE INDEX IF NOT EXISTS "idx_review_drift_status_values_lookup" ON "review"."drift_status_values" ("provider_slug", "source_entity", "source_field");
CREATE TABLE IF NOT EXISTS "review"."drift_gender_values" (
  "drift_id" text NOT NULL,
  "provider_slug" text NOT NULL,
  "source_entity" text NOT NULL,
  "source_field" text NOT NULL,
  "observed_value" text,
  "normalized_candidate" text,
  "observed_count" bigint,
  "review_status" text NOT NULL DEFAULT 'needs_review',
  "decision_id" text,
  "evidence_path" text NOT NULL,
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "pk_review_drift_gender_values" PRIMARY KEY ("drift_id")
);
ALTER TABLE "review"."drift_gender_values" ADD COLUMN IF NOT EXISTS "drift_id" text NOT NULL;
ALTER TABLE "review"."drift_gender_values" ADD COLUMN IF NOT EXISTS "provider_slug" text NOT NULL;
ALTER TABLE "review"."drift_gender_values" ADD COLUMN IF NOT EXISTS "source_entity" text NOT NULL;
ALTER TABLE "review"."drift_gender_values" ADD COLUMN IF NOT EXISTS "source_field" text NOT NULL;
ALTER TABLE "review"."drift_gender_values" ADD COLUMN IF NOT EXISTS "observed_value" text;
ALTER TABLE "review"."drift_gender_values" ADD COLUMN IF NOT EXISTS "normalized_candidate" text;
ALTER TABLE "review"."drift_gender_values" ADD COLUMN IF NOT EXISTS "observed_count" bigint;
ALTER TABLE "review"."drift_gender_values" ADD COLUMN IF NOT EXISTS "review_status" text NOT NULL DEFAULT 'needs_review';
ALTER TABLE "review"."drift_gender_values" ADD COLUMN IF NOT EXISTS "decision_id" text;
ALTER TABLE "review"."drift_gender_values" ADD COLUMN IF NOT EXISTS "evidence_path" text NOT NULL;
ALTER TABLE "review"."drift_gender_values" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz NOT NULL DEFAULT now();
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pk_review_drift_gender_values'
      AND conrelid = 'review.drift_gender_values'::regclass
  ) THEN
    ALTER TABLE "review"."drift_gender_values" ADD CONSTRAINT "pk_review_drift_gender_values" PRIMARY KEY ("drift_id");
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'ck_review_drift_gender_values_review_status'
      AND conrelid = 'review.drift_gender_values'::regclass
  ) THEN
    ALTER TABLE "review"."drift_gender_values" ADD CONSTRAINT "ck_review_drift_gender_values_review_status" CHECK (review_status IN ('needs_review', 'approved', 'rejected', 'deferred_with_human_approval', 'needs_more_evidence'));
  END IF;
END $$;
CREATE INDEX IF NOT EXISTS "idx_review_drift_gender_values_lookup" ON "review"."drift_gender_values" ("provider_slug", "source_entity", "source_field");
CREATE TABLE IF NOT EXISTS "review"."drift_coverage_values" (
  "drift_id" text NOT NULL,
  "provider_slug" text NOT NULL,
  "source_entity" text NOT NULL,
  "source_field" text NOT NULL,
  "observed_value" text,
  "normalized_candidate" text,
  "observed_count" bigint,
  "review_status" text NOT NULL DEFAULT 'needs_review',
  "decision_id" text,
  "evidence_path" text NOT NULL,
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "pk_review_drift_coverage_values" PRIMARY KEY ("drift_id")
);
ALTER TABLE "review"."drift_coverage_values" ADD COLUMN IF NOT EXISTS "drift_id" text NOT NULL;
ALTER TABLE "review"."drift_coverage_values" ADD COLUMN IF NOT EXISTS "provider_slug" text NOT NULL;
ALTER TABLE "review"."drift_coverage_values" ADD COLUMN IF NOT EXISTS "source_entity" text NOT NULL;
ALTER TABLE "review"."drift_coverage_values" ADD COLUMN IF NOT EXISTS "source_field" text NOT NULL;
ALTER TABLE "review"."drift_coverage_values" ADD COLUMN IF NOT EXISTS "observed_value" text;
ALTER TABLE "review"."drift_coverage_values" ADD COLUMN IF NOT EXISTS "normalized_candidate" text;
ALTER TABLE "review"."drift_coverage_values" ADD COLUMN IF NOT EXISTS "observed_count" bigint;
ALTER TABLE "review"."drift_coverage_values" ADD COLUMN IF NOT EXISTS "review_status" text NOT NULL DEFAULT 'needs_review';
ALTER TABLE "review"."drift_coverage_values" ADD COLUMN IF NOT EXISTS "decision_id" text;
ALTER TABLE "review"."drift_coverage_values" ADD COLUMN IF NOT EXISTS "evidence_path" text NOT NULL;
ALTER TABLE "review"."drift_coverage_values" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz NOT NULL DEFAULT now();
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pk_review_drift_coverage_values'
      AND conrelid = 'review.drift_coverage_values'::regclass
  ) THEN
    ALTER TABLE "review"."drift_coverage_values" ADD CONSTRAINT "pk_review_drift_coverage_values" PRIMARY KEY ("drift_id");
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'ck_review_drift_coverage_values_review_status'
      AND conrelid = 'review.drift_coverage_values'::regclass
  ) THEN
    ALTER TABLE "review"."drift_coverage_values" ADD CONSTRAINT "ck_review_drift_coverage_values_review_status" CHECK (review_status IN ('needs_review', 'approved', 'rejected', 'deferred_with_human_approval', 'needs_more_evidence'));
  END IF;
END $$;
CREATE INDEX IF NOT EXISTS "idx_review_drift_coverage_values_lookup" ON "review"."drift_coverage_values" ("provider_slug", "source_entity", "source_field");
CREATE TABLE IF NOT EXISTS "review"."drift_nullability" (
  "drift_id" text NOT NULL,
  "silver_entity" text NOT NULL,
  "column_name" text NOT NULL,
  "provider_slug" text,
  "null_count" bigint,
  "total_count" bigint,
  "null_rate" numeric,
  "review_status" text NOT NULL DEFAULT 'needs_review',
  "decision_id" text,
  "evidence_path" text NOT NULL,
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "pk_review_drift_nullability" PRIMARY KEY ("drift_id")
);
ALTER TABLE "review"."drift_nullability" ADD COLUMN IF NOT EXISTS "drift_id" text NOT NULL;
ALTER TABLE "review"."drift_nullability" ADD COLUMN IF NOT EXISTS "silver_entity" text NOT NULL;
ALTER TABLE "review"."drift_nullability" ADD COLUMN IF NOT EXISTS "column_name" text NOT NULL;
ALTER TABLE "review"."drift_nullability" ADD COLUMN IF NOT EXISTS "provider_slug" text;
ALTER TABLE "review"."drift_nullability" ADD COLUMN IF NOT EXISTS "null_count" bigint;
ALTER TABLE "review"."drift_nullability" ADD COLUMN IF NOT EXISTS "total_count" bigint;
ALTER TABLE "review"."drift_nullability" ADD COLUMN IF NOT EXISTS "null_rate" numeric;
ALTER TABLE "review"."drift_nullability" ADD COLUMN IF NOT EXISTS "review_status" text NOT NULL DEFAULT 'needs_review';
ALTER TABLE "review"."drift_nullability" ADD COLUMN IF NOT EXISTS "decision_id" text;
ALTER TABLE "review"."drift_nullability" ADD COLUMN IF NOT EXISTS "evidence_path" text NOT NULL;
ALTER TABLE "review"."drift_nullability" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz NOT NULL DEFAULT now();
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pk_review_drift_nullability'
      AND conrelid = 'review.drift_nullability'::regclass
  ) THEN
    ALTER TABLE "review"."drift_nullability" ADD CONSTRAINT "pk_review_drift_nullability" PRIMARY KEY ("drift_id");
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'ck_review_drift_nullability_review_status'
      AND conrelid = 'review.drift_nullability'::regclass
  ) THEN
    ALTER TABLE "review"."drift_nullability" ADD CONSTRAINT "ck_review_drift_nullability_review_status" CHECK (review_status IN ('needs_review', 'approved', 'rejected', 'deferred_with_human_approval', 'needs_more_evidence'));
  END IF;
END $$;
CREATE INDEX IF NOT EXISTS "idx_review_drift_nullability_lookup" ON "review"."drift_nullability" ("silver_entity", "column_name", "provider_slug");
CREATE TABLE IF NOT EXISTS "review"."drift_unmapped_or_sparse_fields" (
  "drift_id" text NOT NULL,
  "provider_slug" text NOT NULL,
  "source_entity" text NOT NULL,
  "source_field" text NOT NULL,
  "candidate_concept" text,
  "coverage_note" text,
  "review_status" text NOT NULL DEFAULT 'needs_review',
  "decision_id" text,
  "evidence_path" text NOT NULL,
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "pk_review_drift_unmapped_or_sparse_fields" PRIMARY KEY ("drift_id")
);
ALTER TABLE "review"."drift_unmapped_or_sparse_fields" ADD COLUMN IF NOT EXISTS "drift_id" text NOT NULL;
ALTER TABLE "review"."drift_unmapped_or_sparse_fields" ADD COLUMN IF NOT EXISTS "provider_slug" text NOT NULL;
ALTER TABLE "review"."drift_unmapped_or_sparse_fields" ADD COLUMN IF NOT EXISTS "source_entity" text NOT NULL;
ALTER TABLE "review"."drift_unmapped_or_sparse_fields" ADD COLUMN IF NOT EXISTS "source_field" text NOT NULL;
ALTER TABLE "review"."drift_unmapped_or_sparse_fields" ADD COLUMN IF NOT EXISTS "candidate_concept" text;
ALTER TABLE "review"."drift_unmapped_or_sparse_fields" ADD COLUMN IF NOT EXISTS "coverage_note" text;
ALTER TABLE "review"."drift_unmapped_or_sparse_fields" ADD COLUMN IF NOT EXISTS "review_status" text NOT NULL DEFAULT 'needs_review';
ALTER TABLE "review"."drift_unmapped_or_sparse_fields" ADD COLUMN IF NOT EXISTS "decision_id" text;
ALTER TABLE "review"."drift_unmapped_or_sparse_fields" ADD COLUMN IF NOT EXISTS "evidence_path" text NOT NULL;
ALTER TABLE "review"."drift_unmapped_or_sparse_fields" ADD COLUMN IF NOT EXISTS "updated_at" timestamptz NOT NULL DEFAULT now();
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pk_review_drift_unmapped_or_sparse_fields'
      AND conrelid = 'review.drift_unmapped_or_sparse_fields'::regclass
  ) THEN
    ALTER TABLE "review"."drift_unmapped_or_sparse_fields" ADD CONSTRAINT "pk_review_drift_unmapped_or_sparse_fields" PRIMARY KEY ("drift_id");
  END IF;
END $$;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'ck_review_drift_unmapped_or_sparse_fields_review_status'
      AND conrelid = 'review.drift_unmapped_or_sparse_fields'::regclass
  ) THEN
    ALTER TABLE "review"."drift_unmapped_or_sparse_fields" ADD CONSTRAINT "ck_review_drift_unmapped_or_sparse_fields_review_status" CHECK (review_status IN ('needs_review', 'approved', 'rejected', 'deferred_with_human_approval', 'needs_more_evidence'));
  END IF;
END $$;
CREATE INDEX IF NOT EXISTS "idx_review_drift_sparse_lookup" ON "review"."drift_unmapped_or_sparse_fields" ("provider_slug", "source_entity", "source_field");
CREATE TABLE IF NOT EXISTS "review"."silver_conditions" (
  "provider_slug" text,
  "source_entity" text,
  "source_row_id" text,
  "source_lineage_ref" text,
  "condition_reference" text,
  "member_reference" text,
  "encounter_reference" text,
  "condition_source_code" text,
  "condition_code_hint" text,
  "condition_description" text,
  "record_status" text,
  "review_batch_id" text,
  "loaded_at" timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE "review"."silver_conditions" ADD COLUMN IF NOT EXISTS "provider_slug" text;
ALTER TABLE "review"."silver_conditions" ADD COLUMN IF NOT EXISTS "source_entity" text;
ALTER TABLE "review"."silver_conditions" ADD COLUMN IF NOT EXISTS "source_row_id" text;
ALTER TABLE "review"."silver_conditions" ADD COLUMN IF NOT EXISTS "source_lineage_ref" text;
ALTER TABLE "review"."silver_conditions" ADD COLUMN IF NOT EXISTS "condition_reference" text;
ALTER TABLE "review"."silver_conditions" ADD COLUMN IF NOT EXISTS "member_reference" text;
ALTER TABLE "review"."silver_conditions" ADD COLUMN IF NOT EXISTS "encounter_reference" text;
ALTER TABLE "review"."silver_conditions" ADD COLUMN IF NOT EXISTS "condition_source_code" text;
ALTER TABLE "review"."silver_conditions" ADD COLUMN IF NOT EXISTS "condition_code_hint" text;
ALTER TABLE "review"."silver_conditions" ADD COLUMN IF NOT EXISTS "condition_description" text;
ALTER TABLE "review"."silver_conditions" ADD COLUMN IF NOT EXISTS "record_status" text;
ALTER TABLE "review"."silver_conditions" ADD COLUMN IF NOT EXISTS "review_batch_id" text;
ALTER TABLE "review"."silver_conditions" ADD COLUMN IF NOT EXISTS "loaded_at" timestamptz NOT NULL DEFAULT now();
CREATE INDEX IF NOT EXISTS "idx_review_silver_conditions_lineage" ON "review"."silver_conditions" ("provider_slug", "source_entity", "source_row_id");
CREATE TABLE IF NOT EXISTS "review"."silver_cost_records" (
  "provider_slug" text,
  "source_entity" text,
  "source_row_id" text,
  "source_lineage_ref" text,
  "medication_reference" text,
  "member_reference" text,
  "encounter_reference" text,
  "cost_amount" numeric,
  "cost_date" timestamptz,
  "record_status" text,
  "review_batch_id" text,
  "loaded_at" timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE "review"."silver_cost_records" ADD COLUMN IF NOT EXISTS "provider_slug" text;
ALTER TABLE "review"."silver_cost_records" ADD COLUMN IF NOT EXISTS "source_entity" text;
ALTER TABLE "review"."silver_cost_records" ADD COLUMN IF NOT EXISTS "source_row_id" text;
ALTER TABLE "review"."silver_cost_records" ADD COLUMN IF NOT EXISTS "source_lineage_ref" text;
ALTER TABLE "review"."silver_cost_records" ADD COLUMN IF NOT EXISTS "medication_reference" text;
ALTER TABLE "review"."silver_cost_records" ADD COLUMN IF NOT EXISTS "member_reference" text;
ALTER TABLE "review"."silver_cost_records" ADD COLUMN IF NOT EXISTS "encounter_reference" text;
ALTER TABLE "review"."silver_cost_records" ADD COLUMN IF NOT EXISTS "cost_amount" numeric;
ALTER TABLE "review"."silver_cost_records" ADD COLUMN IF NOT EXISTS "cost_date" timestamptz;
ALTER TABLE "review"."silver_cost_records" ADD COLUMN IF NOT EXISTS "record_status" text;
ALTER TABLE "review"."silver_cost_records" ADD COLUMN IF NOT EXISTS "review_batch_id" text;
ALTER TABLE "review"."silver_cost_records" ADD COLUMN IF NOT EXISTS "loaded_at" timestamptz NOT NULL DEFAULT now();
CREATE INDEX IF NOT EXISTS "idx_review_silver_cost_records_lineage" ON "review"."silver_cost_records" ("provider_slug", "source_entity", "source_row_id");
CREATE TABLE IF NOT EXISTS "review"."silver_coverage_periods" (
  "provider_slug" text,
  "source_entity" text,
  "source_row_id" text,
  "source_lineage_ref" text,
  "member_reference" text,
  "coverage_start_date" date,
  "coverage_end_date" date,
  "coverage_status" text,
  "review_batch_id" text,
  "loaded_at" timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE "review"."silver_coverage_periods" ADD COLUMN IF NOT EXISTS "provider_slug" text;
ALTER TABLE "review"."silver_coverage_periods" ADD COLUMN IF NOT EXISTS "source_entity" text;
ALTER TABLE "review"."silver_coverage_periods" ADD COLUMN IF NOT EXISTS "source_row_id" text;
ALTER TABLE "review"."silver_coverage_periods" ADD COLUMN IF NOT EXISTS "source_lineage_ref" text;
ALTER TABLE "review"."silver_coverage_periods" ADD COLUMN IF NOT EXISTS "member_reference" text;
ALTER TABLE "review"."silver_coverage_periods" ADD COLUMN IF NOT EXISTS "coverage_start_date" date;
ALTER TABLE "review"."silver_coverage_periods" ADD COLUMN IF NOT EXISTS "coverage_end_date" date;
ALTER TABLE "review"."silver_coverage_periods" ADD COLUMN IF NOT EXISTS "coverage_status" text;
ALTER TABLE "review"."silver_coverage_periods" ADD COLUMN IF NOT EXISTS "review_batch_id" text;
ALTER TABLE "review"."silver_coverage_periods" ADD COLUMN IF NOT EXISTS "loaded_at" timestamptz NOT NULL DEFAULT now();
CREATE INDEX IF NOT EXISTS "idx_review_silver_coverage_periods_lineage" ON "review"."silver_coverage_periods" ("provider_slug", "source_entity", "source_row_id");
CREATE TABLE IF NOT EXISTS "review"."silver_encounters" (
  "provider_slug" text,
  "source_entity" text,
  "source_row_id" text,
  "source_lineage_ref" text,
  "encounter_reference" text,
  "member_reference" text,
  "encounter_datetime" timestamptz,
  "coverage_status" text,
  "record_status" text,
  "review_batch_id" text,
  "loaded_at" timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE "review"."silver_encounters" ADD COLUMN IF NOT EXISTS "provider_slug" text;
ALTER TABLE "review"."silver_encounters" ADD COLUMN IF NOT EXISTS "source_entity" text;
ALTER TABLE "review"."silver_encounters" ADD COLUMN IF NOT EXISTS "source_row_id" text;
ALTER TABLE "review"."silver_encounters" ADD COLUMN IF NOT EXISTS "source_lineage_ref" text;
ALTER TABLE "review"."silver_encounters" ADD COLUMN IF NOT EXISTS "encounter_reference" text;
ALTER TABLE "review"."silver_encounters" ADD COLUMN IF NOT EXISTS "member_reference" text;
ALTER TABLE "review"."silver_encounters" ADD COLUMN IF NOT EXISTS "encounter_datetime" timestamptz;
ALTER TABLE "review"."silver_encounters" ADD COLUMN IF NOT EXISTS "coverage_status" text;
ALTER TABLE "review"."silver_encounters" ADD COLUMN IF NOT EXISTS "record_status" text;
ALTER TABLE "review"."silver_encounters" ADD COLUMN IF NOT EXISTS "review_batch_id" text;
ALTER TABLE "review"."silver_encounters" ADD COLUMN IF NOT EXISTS "loaded_at" timestamptz NOT NULL DEFAULT now();
CREATE INDEX IF NOT EXISTS "idx_review_silver_encounters_lineage" ON "review"."silver_encounters" ("provider_slug", "source_entity", "source_row_id");
CREATE TABLE IF NOT EXISTS "review"."silver_medications" (
  "provider_slug" text,
  "source_entity" text,
  "source_row_id" text,
  "source_lineage_ref" text,
  "medication_reference" text,
  "member_reference" text,
  "encounter_reference" text,
  "condition_reference" text,
  "medication_source_code" text,
  "medication_description" text,
  "medication_datetime" timestamptz,
  "record_status" text,
  "review_batch_id" text,
  "loaded_at" timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE "review"."silver_medications" ADD COLUMN IF NOT EXISTS "provider_slug" text;
ALTER TABLE "review"."silver_medications" ADD COLUMN IF NOT EXISTS "source_entity" text;
ALTER TABLE "review"."silver_medications" ADD COLUMN IF NOT EXISTS "source_row_id" text;
ALTER TABLE "review"."silver_medications" ADD COLUMN IF NOT EXISTS "source_lineage_ref" text;
ALTER TABLE "review"."silver_medications" ADD COLUMN IF NOT EXISTS "medication_reference" text;
ALTER TABLE "review"."silver_medications" ADD COLUMN IF NOT EXISTS "member_reference" text;
ALTER TABLE "review"."silver_medications" ADD COLUMN IF NOT EXISTS "encounter_reference" text;
ALTER TABLE "review"."silver_medications" ADD COLUMN IF NOT EXISTS "condition_reference" text;
ALTER TABLE "review"."silver_medications" ADD COLUMN IF NOT EXISTS "medication_source_code" text;
ALTER TABLE "review"."silver_medications" ADD COLUMN IF NOT EXISTS "medication_description" text;
ALTER TABLE "review"."silver_medications" ADD COLUMN IF NOT EXISTS "medication_datetime" timestamptz;
ALTER TABLE "review"."silver_medications" ADD COLUMN IF NOT EXISTS "record_status" text;
ALTER TABLE "review"."silver_medications" ADD COLUMN IF NOT EXISTS "review_batch_id" text;
ALTER TABLE "review"."silver_medications" ADD COLUMN IF NOT EXISTS "loaded_at" timestamptz NOT NULL DEFAULT now();
CREATE INDEX IF NOT EXISTS "idx_review_silver_medications_lineage" ON "review"."silver_medications" ("provider_slug", "source_entity", "source_row_id");
CREATE TABLE IF NOT EXISTS "review"."silver_members" (
  "provider_slug" text,
  "source_entity" text,
  "source_row_id" text,
  "source_lineage_ref" text,
  "member_reference" text,
  "gender_code" text,
  "birth_date" date,
  "record_status" text,
  "review_batch_id" text,
  "loaded_at" timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE "review"."silver_members" ADD COLUMN IF NOT EXISTS "provider_slug" text;
ALTER TABLE "review"."silver_members" ADD COLUMN IF NOT EXISTS "source_entity" text;
ALTER TABLE "review"."silver_members" ADD COLUMN IF NOT EXISTS "source_row_id" text;
ALTER TABLE "review"."silver_members" ADD COLUMN IF NOT EXISTS "source_lineage_ref" text;
ALTER TABLE "review"."silver_members" ADD COLUMN IF NOT EXISTS "member_reference" text;
ALTER TABLE "review"."silver_members" ADD COLUMN IF NOT EXISTS "gender_code" text;
ALTER TABLE "review"."silver_members" ADD COLUMN IF NOT EXISTS "birth_date" date;
ALTER TABLE "review"."silver_members" ADD COLUMN IF NOT EXISTS "record_status" text;
ALTER TABLE "review"."silver_members" ADD COLUMN IF NOT EXISTS "review_batch_id" text;
ALTER TABLE "review"."silver_members" ADD COLUMN IF NOT EXISTS "loaded_at" timestamptz NOT NULL DEFAULT now();
CREATE INDEX IF NOT EXISTS "idx_review_silver_members_lineage" ON "review"."silver_members" ("provider_slug", "source_entity", "source_row_id");
CREATE TABLE IF NOT EXISTS "review"."silver_observations" (
  "provider_slug" text,
  "source_entity" text,
  "source_row_id" text,
  "source_lineage_ref" text,
  "observation_reference" text,
  "member_reference" text,
  "encounter_reference" text,
  "observation_datetime" timestamptz,
  "observation_payload_raw" jsonb,
  "height_cm" numeric,
  "weight_kg" numeric,
  "systolic_bp" numeric,
  "record_status" text,
  "review_batch_id" text,
  "loaded_at" timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE "review"."silver_observations" ADD COLUMN IF NOT EXISTS "provider_slug" text;
ALTER TABLE "review"."silver_observations" ADD COLUMN IF NOT EXISTS "source_entity" text;
ALTER TABLE "review"."silver_observations" ADD COLUMN IF NOT EXISTS "source_row_id" text;
ALTER TABLE "review"."silver_observations" ADD COLUMN IF NOT EXISTS "source_lineage_ref" text;
ALTER TABLE "review"."silver_observations" ADD COLUMN IF NOT EXISTS "observation_reference" text;
ALTER TABLE "review"."silver_observations" ADD COLUMN IF NOT EXISTS "member_reference" text;
ALTER TABLE "review"."silver_observations" ADD COLUMN IF NOT EXISTS "encounter_reference" text;
ALTER TABLE "review"."silver_observations" ADD COLUMN IF NOT EXISTS "observation_datetime" timestamptz;
ALTER TABLE "review"."silver_observations" ADD COLUMN IF NOT EXISTS "observation_payload_raw" jsonb;
ALTER TABLE "review"."silver_observations" ADD COLUMN IF NOT EXISTS "height_cm" numeric;
ALTER TABLE "review"."silver_observations" ADD COLUMN IF NOT EXISTS "weight_kg" numeric;
ALTER TABLE "review"."silver_observations" ADD COLUMN IF NOT EXISTS "systolic_bp" numeric;
ALTER TABLE "review"."silver_observations" ADD COLUMN IF NOT EXISTS "record_status" text;
ALTER TABLE "review"."silver_observations" ADD COLUMN IF NOT EXISTS "review_batch_id" text;
ALTER TABLE "review"."silver_observations" ADD COLUMN IF NOT EXISTS "loaded_at" timestamptz NOT NULL DEFAULT now();
CREATE INDEX IF NOT EXISTS "idx_review_silver_observations_lineage" ON "review"."silver_observations" ("provider_slug", "source_entity", "source_row_id");
INSERT INTO evidence.local_deploy_runs (deployment_id, plan_id, spec_path, spec_checksum, deploy_status, message)
VALUES (
  'local-postgres-workbench-d8a9a208b620',
  '04_5_local_data_workbench_and_drift_resolution_plan',
  'metadata/runtime_specs/local/local_postgres_workbench.yaml',
  'd8a9a208b6208a764bf6a3ae1ec934c77b6b4e18a879236d08bfd8ada04520fd',
  'applied',
  'idempotent local PostgreSQL workbench schema deployed'
)
ON CONFLICT (deployment_id) DO UPDATE SET
  deploy_status = EXCLUDED.deploy_status,
  message = EXCLUDED.message,
  deployed_at = now();
COMMIT;
